<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPageAdmin.master" AutoEventWireup="true" CodeFile="check_post.aspx.cs" Inherits="check_post" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
      <div class="wrapper row3">
  <div class="rounded">
    <main class="container clear"> 
      <div class="sidebar one_third first"> 
        <!-- ################################################################################################ -->
       <h6>Academics</h6>
        <nav class="sdb_holder">
          <ul>
            <li><a href="faculty.aspx"  > Faculty</a> </li>
            <li><a href="house.aspx"  >House Examinations</a></li>
            <li><a href="student_marks.aspx"  >Results</a></li>
            <li><a href="Apply.aspx" >Vacancies</a></li>
          
              
          </ul>

        
        </nav>
        <!-- ################################################################################################ --> 
      </div>
      <!-- ################################################################################################ --> 
      <!-- ################################################################################################ -->
      <div id="content" class="two_third"> 
        <!-- ################################################################################################ -->
        <h1>Choose An Option:</h1>
          <p>
              <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
                  <Columns>
                      <asp:BoundField DataField="id" HeaderText="id" InsertVisible="False" ReadOnly="True" SortExpression="id" />
                      <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                      <asp:BoundField DataField="resume" HeaderText="resume" SortExpression="resume" />
                      <asp:BoundField DataField="dept" HeaderText="dept" SortExpression="dept" />
                      <asp:BoundField DataField="post" HeaderText="post" SortExpression="post" />
                  </Columns>
              </asp:GridView>
          </p>

       
        
        <!-- ################################################################################################ --> 
      </div>
          <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" SelectCommand="SELECT * FROM [applied_post]" DeleteCommand="DELETE FROM [applied_post] WHERE [id] = @id" InsertCommand="INSERT INTO [applied_post] ([name], [resume], [dept], [post]) VALUES (@name, @resume, @dept, @post)" UpdateCommand="UPDATE [applied_post] SET [name] = @name, [resume] = @resume, [dept] = @dept, [post] = @post WHERE [id] = @id">
              <DeleteParameters>
                  <asp:Parameter Name="id" Type="Int32" />
              </DeleteParameters>
              <InsertParameters>
                  <asp:Parameter Name="name" Type="String" />
                  <asp:Parameter Name="resume" Type="String" />
                  <asp:Parameter Name="dept" Type="String" />
                  <asp:Parameter Name="post" Type="String" />
              </InsertParameters>
              <UpdateParameters>
                  <asp:Parameter Name="name" Type="String" />
                  <asp:Parameter Name="resume" Type="String" />
                  <asp:Parameter Name="dept" Type="String" />
                  <asp:Parameter Name="post" Type="String" />
                  <asp:Parameter Name="id" Type="Int32" />
              </UpdateParameters>
      </asp:SqlDataSource>
          <div class="clear"></div>
        </main> 
      </div> 
        </div> 
</asp:Content>

