// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 7.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_stack_vertical(d,a,b){var e=jQuery;var g=e(this);var c=e("li",b);var f=e("<div>").addClass("ws_effect ws_stack_vertical").css({position:"absolute",top:0,left:0,width:"100%",height:"100%",overflow:"hidden"}).appendTo(b);this.go=function(q,j,i){var k=(d.revers?1:-1)*b.height();c.each(function(s){if(i&&s!=j){this.style.zIndex=(Math.max(0,this.style.zIndex-1))}});var p=e(".ws_list",b);var h=e("<div>").css({position:"absolute",left:0,top:0,width:"100%",height:"100%",overflow:"hidden",zIndex:4}).append(e(a.get(i?q:j)).clone()),r=e("<div>").css({position:"absolute",left:0,top:0,width:"100%",height:"100%",overflow:"hidden",zIndex:4}).append(e(a.get(i?j:q)).clone());if(d.responsive<3){h.find("img").css("width","100%");r.find("img").css("width","100%")}if(i){r.appendTo(f);h.appendTo(f)}else{h.insertAfter(p);r.insertAfter(p)}if(!i){p.stop(true,true).hide().css({left:-q+"00%"});if(d.fadeOut){p.fadeIn(d.duration)}else{p.show()}}else{if(d.fadeOut){p.fadeOut(d.duration)}}var o={top:i?k:0};var m={top:i?0:-k*0.5};var n={top:i?0:k};var l={top:(i?1:0)*b.height()*0.5};if(d.support.transform){o={translate:[0,o.top,0]};m={translate:[0,m.top,0]};n={translate:[0,n.top,0]};l={translate:[0,l.top,0]}}wowAnimate(h,o,n,d.duration,d.duration*(i?0:0.1),"easeInOutExpo",function(){g.trigger("effectEnd");h.remove();r.remove()});wowAnimate(r,m,l,d.duration,d.duration*(i?0.1:0),"easeInOutExpo")}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 7.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"stack_vertical",prev:"",next:"",duration:20*100,delay:20*100,width:800,height:600,autoPlay:true,autoPlayVideo:false,playPause:true,stopOnHover:true,loop:false,bullets:0,caption:false,captionEffect:"none",controls:true,responsive:1,fullScreen:true,gestures:2,onBeforeStep:0,images:[{src:"./2.jpg",title:"2"},{src:"./dsc01215.jpg",title:"DSC01215"},{src:"./dsc01224.jpg",title:"DSC01224"},{src:"./dsc01225.jpg",title:"DSC01225"},{src:"./dsc03504.jpg",title:"DSC03504"},{src:"./dsc03505.jpg",title:"DSC03505"},{src:"./dsc03507.jpg",title:"DSC03507"},{src:"./dsc03511.jpg",title:"DSC03511"},{src:"./dsc03525.jpg",title:"DSC03525"},{src:"./dsc03531.jpg",title:"DSC03531"},{src:"./dsc04843.jpg",title:"DSC04843"},{src:"./dsc04846.jpg",title:"DSC04846"},{src:"./dsc04850.jpg",title:"DSC04850"},{src:"./dsc04855.jpg",title:"DSC04855"},{src:"./dsc04865.jpg",title:"DSC04865"},{src:"./dsc04867.jpg",title:"DSC04867"},{src:"./dsc04868.jpg",title:"DSC04868"},{src:"./dsc_9190.jpg",title:"DSC_9190"},{src:"./dsc_9192.jpg",title:"DSC_9192"},{src:"./dsc_9199.jpg",title:"full screen slider",href:"http://wowslider.com/vf"},{src:"./rab_233.jpg",title:"rab 233"}]});